name: ct-anomaly-detection
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - jupyter
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - openpyxl
  - pip:
      - torch
      - torchvision